# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    bouncer_location: 'http://fafnir.bouncer.adip.ly/app_dev.php'
    bouncer_version: '666'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.psr.formatting_listener:
        class: Psr7ControllerBundle\EventListener\PsrListener
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}

    authentication_listener:
        class: Psr7ControllerBundle\EventListener\AuthenticationListener
        arguments: ['%bouncer_location%', '%bouncer_version%']
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}
